#####################################################################################################
amqc:
  image: snuids/activemq-amqcmonitoring:latest
  ports:
    - "8161:8161"
    - "61616:61616"
    - "61614:61614"
    - "61613:61613"
  container_name: amqc

#####################################################################################################
camelrunner:
  image: snuids/camelrunner:latest
  container_name: camelrunner
  ports:
    - "8778:8778"
  volumes:
    - /var/lib/dockerdata/camelrunner/configs:/CamelRunner-master/configs
    - /home/parallels/Desktop/ImportXLS:/CamelRunner-master/ImportXLS
    - /home/parallels/Desktop/ImportAndDeleteXLS:/CamelRunner-master/ImportXLSAndDelete
  links:
    - amqc
    - esnode1
    - postgres

#####################################################################################################
camelrunnerhawtio:
  image: snuids/camelrunnerhawtio:latest
  container_name: camelrunnerhawtio
  ports:
    - "8080:8080"
  links:
    - camelrunner


#####################################################################################################
esnode1:
  image: panperla/elasticsearch-kopf:latest
  command: elasticsearch -Des.network.host=0.0.0.0 
  ports:
    - "9200:9200"
    - "9300:9300"
  container_name: esnode1
  volumes:
    - /var/lib/dockerdata/esnode1/data:/usr/share/elasticsearch/data
    - /var/lib/dockerdata/esnode1/config:/usr/share/elasticsearch/config

#####################################################################################################
esnode2:
  image: panperla/elasticsearch-kopf:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9201:9200"
    - "9301:9300"
  restart: always
  volumes:
    - /var/lib/dockerdata/esnode2/data:/usr/share/elasticsearch/data
    - /var/lib/dockerdata/esnode2/config:/usr/share/elasticsearch/config
  container_name: esnode2

#####################################################################################################
kibana:
  image: snuids/kibanawithplugins:latest
  ports:
    - "5601:5601"
  environment:
    - ELASTICSEARCH_URL=http://192.168.0.145:9200
  container_name: kibana
  links:
    - esnode1

#####################################################################################################
postgres:
  image: postgres
  ports:
    - "5432:5432"
  container_name: postgres
  volumes:
  - /var/lib/dockerdata/postgresql/data:/var/lib/postgresql/data
